//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoteMe.elections.peoples {
	
	
	public partial class home {
		protected System.Web.UI.WebControls.Label nameUserName;
		protected System.Web.UI.WebControls.Label gender;
		protected System.Web.UI.WebControls.Label addr;
		protected System.Web.UI.WebControls.Label mobile;
		protected System.Web.UI.WebControls.Button sout;
	}
}
