//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoteMe.elections.peoples {
	
	
	public partial class Vote {
        protected System.Web.UI.WebControls.RadioButton party1;
        protected System.Web.UI.WebControls.RadioButton party2;
        protected System.Web.UI.WebControls.RadioButton party3;
        protected System.Web.UI.WebControls.RadioButton party4;
        protected System.Web.UI.WebControls.RadioButton party5;
        protected System.Web.UI.WebControls.Label candidate1;
        protected System.Web.UI.WebControls.Label candidate2;
        protected System.Web.UI.WebControls.Label candidate3;
        protected System.Web.UI.WebControls.Label candidate4;
        protected System.Web.UI.WebControls.Label candidate5;
        protected System.Web.UI.WebControls.Button btnSubmit;
        protected System.Web.UI.WebControls.Label name1;
        protected System.Web.UI.WebControls.Label name2;
        protected System.Web.UI.WebControls.Label name3;
        protected System.Web.UI.WebControls.Label name4;
        protected System.Web.UI.WebControls.Label name5;
	}
}
