//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoteMe.elections {
    
    
    public partial class signup {
        
        protected System.Web.UI.HtmlControls.HtmlForm signupform;
        
        protected System.Web.UI.WebControls.TextBox txtUsername;
        
        protected System.Web.UI.WebControls.TextBox txtPasswordEle;
        
        protected System.Web.UI.WebControls.TextBox txtConform;
        
        protected System.Web.UI.WebControls.TextBox txtfName;
        
        protected System.Web.UI.WebControls.TextBox txtlName;
        
        protected System.Web.UI.WebControls.TextBox txtMobile;
        
        protected System.Web.UI.WebControls.RadioButton male;
        
        protected System.Web.UI.WebControls.RadioButton female;
        
        protected System.Web.UI.WebControls.RadioButton other;
        
        protected System.Web.UI.WebControls.TextBox txtAddr;
        
        protected System.Web.UI.WebControls.Button btnSubmit;
        protected System.Web.UI.WebControls.Label msg;
    }
}
